### ISSUE TITLE
Extract `run_interval` from `prosumer.yaml`

### ISSUE THREAD

**Issue by rithviknishad** [rithviknishad/prosumer#7]
- [ ] Support defining `run_interval` of subsystems in `prosumer.yaml` configuration like:
```yaml
run_interval: 5 #seconds
...
```

- [ ] Support overriding `run_interval` of individual subsystem as shown:
```yaml
run_interval: 5

generations:
  - id: 0x001
    run_interval: 10 # <-- This system runs in 10 second intervals.
    ...
```
